services:
  client:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    depends_on:
      - ai-agent
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env

  ai-agent:
    build:
      context: ./ai-agent
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./ai-agent:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: seedsync
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
