# Use the official Node.js image as the base image
FROM node:24-alpine3.21

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Install nodemon globally for development
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose the port the server runs on
EXPOSE 3001

# Start the server using nodemon
CMD ["nodemon", "src/server.js"]