# Base image
FROM python:3.12-slim

# Set work directory
WORKDIR /app

# Install system dependencies for building Python packages
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libffi-dev \
    libssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip to the latest version
RUN pip install --no-cache-dir --upgrade pip

# Copy code
COPY . .

# Install dependencies globally
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Flask or FastAPI port
EXPOSE 8000

# Command to run your app
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--reload" ,"main:app"]