# Base image
FROM python:3.14-slim

# Set work directory
WORKDIR /app

# Copy code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Flask or FastAPI port
EXPOSE 8000

# Command to run your app
CMD ["python", "main.py"]